language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: travis_retry composer update -n

script:
  - vendor/bin/tester -s -p php tests
  - vendor/bin/phpcpd -n src
  - vendor/bin/phpmd src text phpmd_ruleset.xml
  - vendor/bin/phpcs --standard=phpcs_ruleset.xml src
